# Generated by Django 2.2.7 on 2019-11-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findsquirrel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(blank=True, choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], help_text='Age', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='color',
            field=models.CharField(blank=True, choices=[('gray', 'Gray'), ('cinnamon', 'Cinnamon'), ('black', 'Black')], help_text='Primary Fur Color', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(blank=True, choices=[('ground', 'Ground Plane'), ('above', 'Above Ground')], help_text='Location', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, help_text='Other Activities', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Specific Location', max_length=256, null=True),
        ),
    ]
