# Generated by Django 2.2.7 on 2019-11-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findsquirrel', '0002_auto_20191127_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary Fur Color', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location', max_length=128, null=True),
        ),
    ]
